name: drowsiness_detector
description: ESP32-CAM Flutter Drowsiness Detection App

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5
  http: ^1.1.0
  tflite_flutter: ^0.10.4
  image: ^4.0.17
  permission_handler: ^11.0.1
  flutter_local_notifications: ^16.1.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/model/drowsiness_model.tflite
